### ISSUE TITLE
Update keycloak to version 17

### ISSUE THREAD

**Issue by anishdcruz** [lukaszbudnik/keycloak-kubernetes#10]
Thank you so much for this fantastic project.

Do you intend to update the Keycloak to v17? There are several breaking changes in v17 that I've noticed.

**Comment by dryleaf** [comment]
Now Keycloak is at version 19.0.2. Is there any updates on this issue?

**Comment by lukaszbudnik** [comment]
@anishdcruz and @dryleaf I will be working on upgrading to latest 19 version in the upcoming week(s).

**Comment by lukaszbudnik** [comment]
@anishdcruz @dryleaf please checkout main branch it is now updated to latest Keycloak 19.0.3 version.
