### ISSUE TITLE
Question about the TLS certificates referenced inthe keycloak.yaml file

### ISSUE THREAD

**Issue by phiroict** [lukaszbudnik/keycloak-kubernetes#13]
Hi , thanks for your very complete tutorial.
I got stuck on one aspect: 
In the keycloak.yaml, it references a tls key : 
```
            - name: KC_HTTPS_CERTIFICATE_FILE
              value: "/etc/certs/tls.crt"
            - name: KC_HTTPS_CERTIFICATE_KEY_FILE
              value: "/etc/certs/tls.key"
```
Now, I am using the AWS Certificate Manager, which does not allow the export of the private key. Are these certs meant to be these or can these be a self signed certificate? 

Kind regards, Philip Rodrigues.

**Comment by lukaszbudnik** [comment]
This is a self-signed certificate which I generated to have HTTPS TLS everywhere, including ALB and the Keycloak pods. In contrast to terminating HTTPS TLS only at the ALB.
