### ISSUE TITLE
API reports 404 instead of 403

### ISSUE THREAD

**Issue by sbonds** [lukaszbudnik/keycloak-kubernetes#14]
After deploying the Ingress controller `https://api.localtest.me/` would report a 404 Not Found error instead of the expected 403 Forbidden.

The pod logs would have an error similar to:

`I1017 21:58:37.843115       7 store.go:426] "Ignoring ingress because of error while validating ingress class" ingress="namespace/gateway-ingress" error="ingress does not contain a valid IngressClass"
`

The fix is to include an `ingress.class` when creating the Ingress Service.

**Comment by lukaszbudnik** [comment]
Thanks @sbonds for reporting the issue and creating the pull with a fix!

**Comment by sbonds** [comment]
Thanks for making such a fantastic demo! This example really helped me understand how Keycloak could be used with Kubernetes.
