### ISSUE TITLE
Unable to deployment

### ISSUE THREAD

**Issue by jasgeetsingh** [lukaszbudnik/keycloak-kubernetes#2]
Unable to deployment using the steps mentioned

**Comment by lukaszbudnik** [comment]
@jasgeetsingh what is the error you are getting? Can you provide some more information?

**Comment by lukaszbudnik** [comment]
No update since June, closing.

The following script: https://github.com/lukaszbudnik/keycloak-kubernetes/blob/main/deploy-local-cluster.sh is built automatically by GitHub actions on every push and pull request.
