### ISSUE TITLE
Can i access the keycloak aws setup using the load balancer url

### ISSUE THREAD

**Issue by jainmohit** [lukaszbudnik/keycloak-kubernetes#25]

**Comment by lukaszbudnik** [comment]
Yes, you can do this. However, the AWS load balancer DNS is not too user friendly. Also, for security reasons, this is not the best practices to use default DNS names which look like `1234567890.us-west-2.elb.amazonaws.com`.

**Comment by lukaszbudnik** [comment]
Closing as no follow up questions.
