### ISSUE TITLE
Page hosted is unreachable

### ISSUE THREAD

**Issue by MRiabov** [lukaszbudnik/keycloak-kubernetes#26]
Hey Lukasz! Nice tutorial, and I've almost completed it, but I'm stuck on actually accessing the page.

So, I've executed all the steps (numerous times), but...
![image](https://user-images.githubusercontent.com/108194191/224325312-deca72b4-c492-4bee-ada8-0b470b02a593.png)

If you know what might be the reason, would be nice if you tell, because I've been stuck on it for 3 days already.
Thanks in advance!

**Comment by lukaszbudnik** [comment]
When I open the page from the screenshot it redirects me to some German hosting provider. You need to be the owner of the domain, generate valid HTTPS cert and then follow the steps in the tutorial.
