### ISSUE TITLE
Wrong port number on Ingress

### ISSUE THREAD

**Issue by truongnh1992** [lukaszbudnik/keycloak-kubernetes#6]
In the service declaration https://github.com/lukaszbudnik/keycloak-kubernetes/blob/main/keycloak.yaml#L10, you specified port 443.
So, in the [Keycloak Ingress](https://github.com/lukaszbudnik/keycloak-kubernetes/blob/main/keycloak-ingress.yaml#L22), you have to use `port number: 443` rather than 8443.

**Comment by lukaszbudnik** [comment]
Thanks for reporting this. Fixed in pull #7. The pull also contains a new script that deploys Keycloak cluster to Kubernetes cluster. This script is called by GitHub actions on every push and pull request.
