### ISSUE TITLE
Keycloak config

### ISSUE THREAD

**Issue by Robinyo** [lukaszbudnik/keycloak-kubernetes#8]
See: https://github.com/adorsys/keycloak-config-cli

**Comment by lukaszbudnik** [comment]
Could you elaborate on the goal of this issue? I only see a link to keycloak config cli repo.

**Comment by Robinyo** [comment]
Sure, it is not really an issue it is a link to a project that I thought might be of interest.

You can also import a realm by copying it to your image:

```
FROM quay.io/keycloak/keycloak:15.0.2

COPY json /tmp
```

And:

```
KEYCLOAK_IMPORT=/tmp/development-realm.json
KEYCLOAK_MIGRATION_STRATEGY=OVERWRITE_EXISTING
```

For example: https://github.com/Robinyo/serendipity-2.0/tree/main/backend/services/serendipity-identity-server

**Comment by lukaszbudnik** [comment]
Closing this issue. main branch has been updated to 19.0.3 and also import works a little bit different.
